### ISSUE TITLE
It looks like the ch.enterag.sqlparser.generated package is missing.

### ISSUE THREAD

**Issue by ldev27** [sfa-siard/SqlParser#2]
It looks like the ch.enterag.sqlparser.generated package is missing. Please confirm.
![SqlParser_Error](https://user-images.githubusercontent.com/56239351/67615025-c9742a80-f801-11e9-8df2-b1223f18983c.png)

**Comment by HartwigThomas** [comment]
When you execute the build, that package is generated (hence the name) from the
grammar .g4 files in /var. 

Thus the package is not missing. The target "generate" of the build is mentioned and described in the manual.

The same comment obtains for the project SiardApi. The "generated" package is generated from the metadata.xsd for SIARD.
